# Generated by Django 6.0.8 on 2026-09-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite_ohada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptecomptable',
            name='entreprise_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='entreprise_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='exercicecomptable',
            name='entreprise_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='journalcomptable',
            name='entreprise_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='journalcomptable',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
        migrations.AlterUniqueTogether(
            name='comptecomptable',
            unique_together={('entreprise_id', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='ecriturecomptable',
            unique_together={('entreprise_id', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='exercicecomptable',
            unique_together={('entreprise_id', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='journalcomptable',
            unique_together={('entreprise_id', 'code')},
        ),
    ]
