# Generated by Django 5.2.17 on 2026-09-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite_ohada', '0002_comptecomptable_entreprise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptecomptable',
            name='categorie',
            field=models.CharField(choices=[('bilan', 'Bilan'), ('resultat', 'Résultat'), ('hors_bilan', 'Hors bilan'), ('analytique', 'Analytique')], default='bilan', max_length=20, verbose_name='Catégorie'),
        ),
    ]
