# Generated by Django 5.2.17 on 2026-10-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite_ohada', '0003_alter_comptecomptable_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneecriturecomptable',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='IntegrationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_id', models.CharField(db_index=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ecriture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_receipts', to='comptabilite_ohada.ecriturecomptable')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entreprise_id', 'idempotency_key'), name='uniq_accounting_receipt_tenant_key')],
            },
        ),
    ]
